# Generated by Django 5.1.6 on 2025-02-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_estado', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='leiloeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('id_leiloeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leiloeiro')),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(max_length=10)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('id_leiloeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leiloeiro')),
            ],
        ),
    ]
