# Generated by Django 5.1.6 on 2025-02-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='id_leiloeiro',
        ),
    ]
