# Generated by Django 5.1.6 on 2025-02-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_anexo_id_leiloeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='id_leiloeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leiloeiro'),
        ),
    ]
