# Generated by Django 5.1.6 on 2025-02-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leiloeiro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leiloeiro',
            name='user',
        ),
    ]
